### ISSUE TITLE
Processes are killed with SIGABRT on high load

### ISSUE THREAD

**Issue by cebe** [MultiChain/multichain#42]
As it is unrelated to #38, I am making a new issue here.

The following error happens occasionally on different nodes in the blockchain (systemd journal):

```
Jan 24 20:18:45 htzn022 systemd[1]: multichain-testcoin@9612.service: Unit entered failed state.
Jan 24 20:18:45 htzn022 systemd[1]: multichain-testcoin@9612.service: Failed with result 'exit-code'.
Jan 24 20:18:46 htzn022 multichaind[30469]: *** Error in `/opt/multichain/testcoin/bin/multichaind': double free or corruption (out): 0x00007f6e28003010 ***
Jan 24 20:18:46 htzn022 multichaind[30469]: ======= Backtrace: =========
Jan 24 20:18:46 htzn022 systemd[1]: multichain-testcoin@9605.service: Main process exited, code=killed, status=6/ABRT
Jan 24 20:18:46 htzn022 systemd[1]: multichain-testcoin@9605.service: Unit entered failed state.
Jan 24 20:18:46 htzn022 systemd[1]: multichain-testcoin@9605.service: Failed with result 'signal'.
```

I was able to catch it with gdb:

```
# gdb --args /opt/multichain/testcoin/bin/multichaind testcoin@127.0.0.1:9200 -datadir="/var/lib/multichain/testcoin/node-9612"
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /opt/multichain/testcoin/bin/multichaind...done.
(gdb) run
Starting program: /opt/multichain/testcoin/bin/multichaind testcoin@127.0.0.1:9200 -datadir=/var/lib/multichain/testcoin/node-9612
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

MultiChain 1.0.2.1 Daemon (latest protocol 10009)

[New Thread 0x7ffff6654700 (LWP 13046)]
[New Thread 0x7ffff5e53700 (LWP 13047)]
[New Thread 0x7ffff5652700 (LWP 13048)]
[New Thread 0x7ffff4e51700 (LWP 13049)]
[New Thread 0x7fffe7fff700 (LWP 13050)]
[New Thread 0x7fffe77fe700 (LWP 13051)]
[New Thread 0x7fffe6ffd700 (LWP 13052)]
[New Thread 0x7fffe67fc700 (LWP 13053)]
[New Thread 0x7fffe5ffb700 (LWP 13054)]
[New Thread 0x7fffe57fa700 (LWP 13055)]
[New Thread 0x7fffe4ff9700 (LWP 13056)]
[New Thread 0x7fffc7fff700 (LWP 13057)]
Chain testcoin already exists, adding 127.0.0.1:9200 to list of peers

[New Thread 0x7fffc77fe700 (LWP 13146)]
[New Thread 0x7fffc6ffd700 (LWP 13147)]
[New Thread 0x7fffc67fc700 (LWP 13148)]
[New Thread 0x7fffc5ffb700 (LWP 13149)]
[New Thread 0x7fffc57fa700 (LWP 13150)]
[New Thread 0x7fffc4ff9700 (LWP 13151)]
[New Thread 0x7fffbffff700 (LWP 13152)]
[New Thread 0x7fffbf7fe700 (LWP 13153)]
[New Thread 0x7fffbeffd700 (LWP 13154)]
Other nodes can connect to this node using:
multichaind testcoin@178.63.41.76:9612

0 of 9 blocks rescanned
[New Thread 0x7fffbe7fc700 (LWP 13275)]
[Thread 0x7fffbe7fc700 (LWP 13275) exited]
[New Thread 0x7fffbdffb700 (LWP 13276)]
[New Thread 0x7fffbd7fa700 (LWP 13277)]
[New Thread 0x7fffbcff9700 (LWP 13278)]
[Thread 0x7fffbdffb700 (LWP 13276) exited]
[New Thread 0x7fff93fff700 (LWP 13279)]
[New Thread 0x7fff937fe700 (LWP 13280)]
[New Thread 0x7fff92ffd700 (LWP 13281)]
[New Thread 0x7fff927fc700 (LWP 13282)]
[New Thread 0x7fff91ffb700 (LWP 13283)]
Node ready.

*** Error in `/opt/multichain/testcoin/bin/multichaind': double free or corruption (!prev): 0x00007fff9801a840 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x70bcb)[0x7ffff69e0bcb]
/lib/x86_64-linux-gnu/libc.so.6(+0x76f96)[0x7ffff69e6f96]
/lib/x86_64-linux-gnu/libc.so.6(+0x777de)[0x7ffff69e77de]
/opt/multichain/testcoin/bin/multichaind[0x4d0600]
/opt/multichain/testcoin/bin/multichaind[0x4adf2b]
/opt/multichain/testcoin/bin/multichaind[0x537b4c]
/opt/multichain/testcoin/bin/multichaind[0x51ba45]
/opt/multichain/testcoin/bin/multichaind[0x535ea5]
/opt/multichain/testcoin/bin/multichaind[0x852354]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7494)[0x7ffff6d16494]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7ffff6a58aff]
======= Memory map: ========
00400000-00cc6000 r-xp 00000000 09:02 168429917                          /opt/multichain/testcoin/bin/multichaind-wdebug
00ec6000-00ef4000 r--p 008c6000 09:02 168429917                          /opt/multichain/testcoin/bin/multichaind-wdebug
00ef4000-00f07000 rw-p 008f4000 09:02 168429917                          /opt/multichain/testcoin/bin/multichaind-wdebug
00f07000-00fbd000 rw-p 00000000 00:00 0                                  [heap]
00fbd000-00fbe000 rw-p 00000000 00:00 0                                  [heap]
00fbe000-00fd0000 rw-p 00000000 00:00 0                                  [heap]
00fd0000-00fd1000 rw-p 00000000 00:00 0                                  [heap]
00fd1000-01ae5000 rw-p 00000000 00:00 0                                  [heap]
01ae5000-01ae6000 rw-p 00000000 00:00 0                                  [heap]
01ae6000-01d71000 rw-p 00000000 00:00 0                                  [heap]
7fff78000000-7fff78021000 rw-p 00000000 00:00 0 
7fff78021000-7fff7c000000 ---p 00000000 00:00 0 
7fff7c000000-7fff7c021000 rw-p 00000000 00:00 0 
7fff7c021000-7fff80000000 ---p 00000000 00:00 0 
7fff80000000-7fff80228000 rw-p 00000000 00:00 0 
7fff80228000-7fff84000000 ---p 00000000 00:00 0 
7fff84000000-7fff84021000 rw-p 00000000 00:00 0 
7fff84021000-7fff88000000 ---p 00000000 00:00 0 
7fff88000000-7fff88021000 rw-p 00000000 00:00 0 
7fff88021000-7fff8c000000 ---p 00000000 00:00 0 
7fff8c000000-7fff8c021000 rw-p 00000000 00:00 0 
7fff8c021000-7fff90000000 ---p 00000000 00:00 0 
7fff917fb000-7fff917fc000 ---p 00000000 00:00 0 
7fff917fc000-7fff91ffc000 rw-p 00000000 00:00 0 
7fff91ffc000-7fff91ffd000 ---p 00000000 00:00 0 
7fff91ffd000-7fff927fd000 rw-p 00000000 00:00 0 
7fff927fd000-7fff927fe000 ---p 00000000 00:00 0 
7fff927fe000-7fff92ffe000 rw-p 00000000 00:00 0 
7fff92ffe000-7fff92fff000 ---p 00000000 00:00 0 
7fff92fff000-7fff937ff000 rw-p 00000000 00:00 0 
7fff937ff000-7fff93800000 ---p 00000000 00:00 0 
7fff93800000-7fff94000000 rw-p 00000000 00:00 0 
7fff94000000-7fff9410c000 rw-p 00000000 00:00 0 
7fff9410c000-7fff98000000 ---p 00000000 00:00 0 
7fff98000000-7fff98054000 rw-p 00000000 00:00 0 
7fff98054000-7fff9c000000 ---p 00000000 00:00 0 
7fff9c000000-7fff9c054000 rw-p 00000000 00:00 0 
7fff9c054000-7fffa0000000 ---p 00000000 00:00 0 
7fffa0000000-7fffa0057000 rw-p 00000000 00:00 0 
7fffa0057000-7fffa4000000 ---p 00000000 00:00 0 
7fffa4000000-7fffa409f000 rw-p 00000000 00:00 0 
7fffa409f000-7fffa8000000 ---p 00000000 00:00 0 
7fffa8000000-7fffa8051000 rw-p 00000000 00:00 0 
7fffa8051000-7fffac000000 ---p 00000000 00:00 0 
7fffac000000-7fffac09c000 rw-p 00000000 00:00 0 
7fffac09c000-7fffb0000000 ---p 00000000 00:00 0 
7fffb0000000-7fffb0081000 rw-p 00000000 00:00 0 
7fffb0081000-7fffb4000000 ---p 00000000 00:00 0 
7fffb4000000-7fffb4061000 rw-p 00000000 00:00 0 
7fffb4061000-7fffb8000000 ---p 00000000 00:00 0 
7fffb8000000-7fffb8021000 rw-p 00000000 00:00 0 
7fffb8021000-7fffbc000000 ---p 00000000 00:00 0 
7fffbc7f9000-7fffbc7fa000 ---p 00000000 00:00 0 
7fffbc7fa000-7fffbcffa000 rw-p 00000000 00:00 0 
7fffbcffa000-7fffbcffb000 ---p 00000000 00:00 0 
7fffbcffb000-7fffbd7fb000 rw-p 00000000 00:00 0 
7fffbd7fb000-7fffbd7fc000 ---p 00000000 00:00 0 
7fffbd7fc000-7fffbdffc000 rw-p 00000000 00:00 0 
7fffbdffc000-7fffbdffd000 ---p 00000000 00:00 0 
7fffbdffd000-7fffbe7fd000 rw-p 00000000 00:00 0 
7fffbe7fd000-7fffbe7fe000 ---p 00000000 00:00 0 
7fffbe7fe000-7fffbeffe000 rw-p 00000000 00:00 0 
7fffbeffe000-7fffbefff000 ---p 00000000 00:00 0 
7fffbefff000-7fffbf7ff000 rw-p 00000000 00:00 0 
7fffbf7ff000-7fffbf800000 ---p 00000000 00:00 0 
7fffbf800000-7fffc0000000 rw-p 00000000 00:00 0 
7fffc0000000-7fffc0023000 rw-p 00000000 00:00 0 
7fffc0023000-7fffc4000000 ---p 00000000 00:00 0 
7fffc47f9000-7fffc47fa000 ---p 00000000 00:00 0 
7fffc47fa000-7fffc4ffa000 rw-p 00000000 00:00 0 
7fffc4ffa000-7fffc4ffb000 ---p 00000000 00:00 0 
7fffc4ffb000-7fffc57fb000 rw-p 00000000 00:00 0 
7fffc57fb000-7fffc57fc000 ---p 00000000 00:00 0 
7fffc57fc000-7fffc5ffc000 rw-p 00000000 00:00 0 
7fffc5ffc000-7fffc5ffd000 ---p 00000000 00:00 0 
7fffc5ffd000-7fffc67fd000 rw-p 00000000 00:00 0 
7fffc67fd000-7fffc67fe000 ---p 00000000 00:00 0 
7fffc67fe000-7fffc6ffe000 rw-p 00000000 00:00 0 
7fffc6ffe000-7fffc6fff000 ---p 00000000 00:00 0 
7fffc6fff000-7fffc77ff000 rw-p 00000000 00:00 0 
7fffc77ff000-7fffc7800000 ---p 00000000 00:00 0 
7fffc7800000-7fffc8000000 rw-p 00000000 00:00 0 
7fffc8000000-7fffc8023000 rw-p 00000000 00:00 0 
7fffc8023000-7fffcc000000 ---p 00000000 00:00 0 
7fffcc000000-7fffcc023000 rw-p 00000000 00:00 0 
7fffcc023000-7fffd0000000 ---p 00000000 00:00 0 
7fffd0000000-7fffd0023000 rw-p 00000000 00:00 0 
7fffd0023000-7fffd4000000 ---p 00000000 00:00 0 
7fffd4000000-7fffd4023000 rw-p 00000000 00:00 0 
7fffd4023000-7fffd8000000 ---p 00000000 00:00 0 
7fffd8000000-7fffd8023000 rw-p 00000000 00:00 0 
7fffd8023000-7fffdc000000 ---p 00000000 00:00 0 
7fffdc000000-7fffdc023000 rw-p 00000000 00:00 0 
7fffdc023000-7fffe0000000 ---p 00000000 00:00 0 
7fffe0000000-7fffe0023000 rw-p 00000000 00:00 0 
7fffe0023000-7fffe4000000 ---p 00000000 00:00 0 
7fffe4071000-7fffe47f9000 rw-p 00000000 00:00 0 
7fffe47f9000-7fffe47fa000 ---p 00000000 00:00 0 
7fffe47fa000-7fffe4ffa000 rw-p 00000000 00:00 0 
7fffe4ffa000-7fffe4ffb000 ---p 00000000 00:00 0 
7fffe4ffb000-7fffe57fb000 rw-p 00000000 00:00 0 
7fffe57fb000-7fffe57fc000 ---p 00000000 00:00 0 
7fffe57fc000-7fffe5ffc000 rw-p 00000000 00:00 0 
7fffe5ffc000-7fffe5ffd000 ---p 00000000 00:00 0 
7fffe5ffd000-7fffe67fd000 rw-p 00000000 00:00 0 
7fffe67fd000-7fffe67fe000 ---p 00000000 00:00 0 
7fffe67fe000-7fffe6ffe000 rw-p 00000000 00:00 0 
7fffe6ffe000-7fffe6fff000 ---p 00000000 00:00 0 
7fffe6fff000-7fffe77ff000 rw-p 00000000 00:00 0 
7fffe77ff000-7fffe7800000 ---p 00000000 00:00 0 
7fffe7800000-7fffe8000000 rw-p 00000000 00:00 0 
7fffe8000000-7fffe8023000 rw-p 00000000 00:00 0 
7fffe8023000-7fffec000000 ---p 00000000 00:00 0 
7fffec000000-7fffec023000 rw-p 00000000 00:00 0 
7fffec023000-7ffff0000000 ---p 00000000 00:00 0 
7ffff0000000-7ffff0023000 rw-p 00000000 00:00 0 
7ffff0023000-7ffff4000000 ---p 00000000 00:00 0 
7ffff4061000-7ffff4651000 rw-p 00000000 00:00 0 
7ffff4651000-7ffff4652000 ---p 00000000 00:00 0 
7ffff4652000-7ffff4e52000 rw-p 00000000 00:00 0 
7ffff4e52000-7ffff4e53000 ---p 00000000 00:00 0 
7ffff4e53000-7ffff5653000 rw-p 00000000 00:00 0 
7ffff5653000-7ffff5654000 ---p 00000000 00:00 0 
7ffff5654000-7ffff5e54000 rw-p 00000000 00:00 0 
7ffff5e54000-7ffff5e55000 ---p 00000000 00:00 0 
7ffff5e55000-7ffff6655000 rw-p 00000000 00:00 0 
7ffff6655000-7ffff6970000 r--p 00000000 09:02 188876800                  /usr/lib/locale/locale-archive
7ffff6970000-7ffff6b05000 r-xp 00000000 09:02 51251940                   /lib/x86_64-linux-gnu/libc-2.24.so
7ffff6b05000-7ffff6d05000 ---p 00195000 09:02 51251940                   /lib/x86_64-linux-gnu/libc-2.24.so
7ffff6d05000-7ffff6d09000 r--p 00195000 09:02 51251940                   /lib/x86_64-linux-gnu/libc-2.24.so
7ffff6d09000-7ffff6d0b000 rw-p 00199000 09:02 51251940                   /lib/x86_64-linux-gnu/libc-2.24.so
7ffff6d0b000-7ffff6d0f000 rw-p 00000000 00:00 0 
7ffff6d0f000-7ffff6d27000 r-xp 00000000 09:02 51251922                   /lib/x86_64-linux-gnu/libpthread-2.24.so
7ffff6d27000-7ffff6f26000 ---p 00018000 09:02 51251922                   /lib/x86_64-linux-gnu/libpthread-2.24.so
7ffff6f26000-7ffff6f27000 r--p 00017000 09:02 51251922                   /lib/x86_64-linux-gnu/libpthread-2.24.so
7ffff6f27000-7ffff6f28000 rw-p 00018000 09:02 51251922                   /lib/x86_64-linux-gnu/libpthread-2.24.so
7ffff6f28000-7ffff6f2c000 rw-p 00000000 00:00 0 
7ffff6f2c000-7ffff6f42000 r-xp 00000000 09:02 51252004                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7ffff6f42000-7ffff7141000 ---p 00016000 09:02 51252004                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7ffff7141000-7ffff7142000 r--p 00015000 09:02 51252004                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7ffff7142000-7ffff7143000 rw-p 00016000 09:02 51252004                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7ffff7143000-7ffff7246000 r-xp 00000000 09:02 51251895                   /lib/x86_64-linux-gnu/libm-2.24.so
7ffff7246000-7ffff7445000 ---p 00103000 09:02 51251895                   /lib/x86_64-linux-gnu/libm-2.24.so
7ffff7445000-7ffff7446000 r--p 00102000 09:02 51251895                   /lib/x86_64-linux-gnu/libm-2.24.so
7ffff7446000-7ffff7447000 rw-p 00103000 09:02 51251895                   /lib/x86_64-linux-gnu/libm-2.24.so
7ffff7447000-7ffff75b9000 r-xp 00000000 09:02 188883309                  /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22
7ffff75b9000-7ffff77b9000 ---p 00172000 09:02 188883309                  /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22
7ffff77b9000-7ffff77c3000 r--p 00172000 09:02 188883309                  /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22
7ffff77c3000-7ffff77c5000 rw-p 0017c000 09:02 188883309                  /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22
7ffff77c5000-7ffff77c9000 rw-p 00000000 00:00 0 
7ffff77c9000-7ffff77d0000 r-xp 00000000 09:02 51251975                   /lib/x86_64-linux-gnu/librt-2.24.so
7ffff77d0000-7ffff79cf000 ---p 00007000 09:02 51251975                   /lib/x86_64-linux-gnu/librt-2.24.so
7ffff79cf000-7ffff79d0000 r--p 00006000 09:02 51251975                   /lib/x86_64-linux-gnu/librt-2.24.so
7ffff79d0000-7ffff79d1000 rw-p 00007000 09:02 51251975                   /lib/x86_64-linux-gnu/librt-2.24.so
7ffff79d1000-7ffff79d4000 r-xp 00000000 09:02 51252035                   /lib/x86_64-linux-gnu/libanl-2.24.so
7ffff79d4000-7ffff7bd3000 ---p 00003000 09:02 51252035                   /lib/x86_64-linux-gnu/libanl-2.24.so
7ffff7bd3000-7ffff7bd4000 r--p 00002000 09:02 51252035                   /lib/x86_64-linux-gnu/libanl-2.24.so
7ffff7bd4000-7ffff7bd5000 rw-p 00003000 09:02 51252035                   /lib/x86_64-linux-gnu/libanl-2.24.so
7ffff7bd5000-7ffff7bd8000 r-xp 00000000 09:02 51252000                   /lib/x86_64-linux-gnu/libdl-2.24.so
7ffff7bd8000-7ffff7dd7000 ---p 00003000 09:02 51252000                   /lib/x86_64-linux-gnu/libdl-2.24.so
7ffff7dd7000-7ffff7dd8000 r--p 00002000 09:02 51252000                   /lib/x86_64-linux-gnu/libdl-2.24.so
7ffff7dd8000-7ffff7dd9000 rw-p 00003000 09:02 51252000                   /lib/x86_64-linux-gnu/libdl-2.24.so
7ffff7dd9000-7ffff7dfc000 r-xp 00000000 09:02 51251905                   /lib/x86_64-linux-gnu/ld-2.24.so
7ffff7e5f000-7ffff7e60000 rw-p 00000000 00:00 0 
7ffff7e60000-7ffff7e61000 r--s 00000000 09:02 130286581                  /var/lib/multichain/testcoin/node-9612/testcoin/chainstate/000005.ldb
7ffff7e61000-7ffff7e62000 r--s 00000000 09:02 130286451                  /var/lib/multichain/testcoin/node-9612/testcoin/permissions.db/000010.ldb
7ffff7e62000-7ffff7ee4000 r--s 00000000 09:02 130286480                  /var/lib/multichain/testcoin/node-9612/testcoin/blocks/index/000005.ldb
7ffff7ee4000-7ffff7ee5000 r--s 00000000 09:02 130286354                  /var/lib/multichain/testcoin/node-9612/testcoin/entities.db/000005.ldb
7ffff7ee5000-7ffff7fe6000 rw-p 00000000 00:00 0 
7ffff7fe6000-7ffff7fe7000 r--s 00000000 09:02 130286573                  /var/lib/multichain/testcoin/node-9612/testcoin/permissions.db/000005.ldb
7ffff7fe7000-7ffff7fe8000 r--s 00000000 09:02 130286481                  /var/lib/multichain/testcoin/node-9612/testcoin/permissions.db/000008.ldb
7ffff7fe8000-7ffff7fee000 rw-p 00000000 00:00 0 
7ffff7fee000-7ffff7ff5000 r--s 00000000 09:02 188883703                  /usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache
7ffff7ff5000-7ffff7ff8000 rw-p 00000000 00:00 0 
7ffff7ff8000-7ffff7ffa000 r--p 00000000 00:00 0                          [vvar]
7ffff7ffa000-7ffff7ffc000 r-xp 00000000 00:00 0                          [vdso]
7ffff7ffc000-7ffff7ffd000 r--p 00023000 09:02 51251905                   /lib/x86_64-linux-gnu/ld-2.24.so
7ffff7ffd000-7ffff7ffe000 rw-p 00024000 09:02 51251905                   /lib/x86_64-linux-gnu/ld-2.24.so
7ffff7ffe000-7ffff7fff000 rw-p 00000000 00:00 0 
7ffffffde000-7ffffffff000 rw-p 00000000 00:00 0                          [stack]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

Thread 28 "bitcoin-msghand" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff937fe700 (LWP 13280)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) backtrace
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff69a43fa in __GI_abort () at abort.c:89
#2  0x00007ffff69e0bd0 in __libc_message (do_abort=do_abort@entry=2, 
    fmt=fmt@entry=0x7ffff6ad5dd0 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff69e6f96 in malloc_printerr (action=3, 
    str=0x7ffff6ad5e48 "double free or corruption (!prev)", ptr=<optimized out>, ar_ptr=<optimized out>)
    at malloc.c:5049
#4  0x00007ffff69e77de in _int_free (av=0x7fff98000020, p=0x7fff9801a830, have_lock=0) at malloc.c:3905
#5  0x00000000004d0600 in std::deque<CNetMessage, std::allocator<CNetMessage> >::erase(std::_Deque_iterator<CNetMessage, CNetMessage&, CNetMessage*>, std::_Deque_iterator<CNetMessage, CNetMessage&, CNetMessage*>) ()
#6  0x00000000004adf2b in ProcessMessages (pfrom=0x7fff880076d0) at core/main.cpp:6829
#7  0x0000000000537b4c in boost::signals2::detail::signal1_impl<bool, CNode*, boost::signals2::optional_last_value<bool>, int, std::less<int>, boost::function<bool (CNode*)>, boost::function<bool (boost::signals2::connection const&, CNode*)>, boost::signals2::mutex>::operator()(CNode*) ()
#8  0x000000000051ba45 in boost::signals2::signal1<bool, CNode*, boost::signals2::optional_last_value<bool>, int, std::less<int>, boost::function<bool (CNode*)>, boost::function<bool (boost::signals2::connection const&, CNode*)>, boost::signals2::mutex>::operator()(CNode*) (arg1=<optimized out>, 
    this=<optimized out>) at /usr/local/include/boost/signals2/detail/signal_template.hpp:718
#9  ThreadMessageHandler () at net/net.cpp:1643
#10 0x0000000000535ea5 in void TraceThread<void (*)()>(char const*, void (*)()) ()
#11 0x0000000000852354 in thread_proxy ()
#12 0x00007ffff6d16494 in start_thread (arg=0x7fff937fe700) at pthread_create.c:333
#13 0x00007ffff6a58aff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
(gdb) 
```

I got the same error with the same stack trace multiple times on different nodes in the blockchain.
This one is using the 1.0.2.1-wdebug build, but I have also seen it with 1.0.2.1 without debug symbols so I think it is unrelated to the build type.

I have sent you an email with the blockchain directory of one affected node.

**Comment by gidgreen** [comment]
Thanks. Could you please stop a node exhibiting these problems and send its zipped blockchain directory to multichain dot debug at gmail?

**Comment by cebe** [comment]
> I have sent you an email with the blockchain directory of one affected node.

I already did that.

**Comment by mike31** [comment]
Unfortunately we don't see your email.

Anyway, the error you see is quite strange as it is in the code we didn't modify for more than a year. I suspect it is something to do with the flavour of your Linux and/or amount of RAM on your system. Can you please tell what system do you use?

Another thing, which may help. Start multichain with -debug=net -debug=mchn runtime parameters, then post the tail of the debug.log (~50 rows).
